resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: docker.io/teliaoss/github-pr-resource

- name: file-url
  type: registry-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: git-clone-resource
  type: git
  webhook_token: ((substrate-webhook-token))
  check_every: 12h
  source:
    branch: polkadot-v0.9.42
    uri: git@github.com:gensyn-ai/substrate.git
    private_key: ((rosarot-ssh-key))
    private_key_username: ((rosarot-gh-username))

- name: git-pull-request-resource
  type: pull-request
  webhook_token: ((substrate-webhook-token))
  check_every: 12h
  source:
    base_branch: polkadot-v0.9.42
    repository: gensyn-ai/substrate
    access_token: ((rosarot-github-token))

- name: env-glibc
  type: registry-image
  source:
    repository: quay.io/drahnr/rust-glibc-builder

jobs:
####################################################################################
#                              P U L L - R E Q U E S T
####################################################################################
  - name: pr-verify
    build_logs_to_retain: 10
    public: true
    max_in_flight: 3
    plan:
    - in_parallel:
      - get: git-pull-request-resource
        resource: git-pull-request-resource
        version: every
        trigger: true

      - get: env-glibc

    - in_parallel:
      - put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          context: cargo-fmt
          status: pending

      - put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          context: taplo-fmt
          status: pending

      - put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          context: cargo-build
          status: pending

      - put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          context: cargo-test
          status: pending

      - put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          context: cargo-clippy
          status: pending

    - in_parallel:
      - task: pr-check-rust-formatting
        timeout: 15m
        image: env-glibc
        config:
          platform: linux
          inputs:
          - name: git-pull-request-resource
          run:
            # user: root
            dir: git-pull-request-resource
            path: sh
            args:
            - -exc
            - |
              cargo +nightly fmt --version

              cargo +nightly fmt -- --check

        on_success:
          put: git-pull-request-resource
          params:
            path: git-pull-request-resource
            context: cargo-fmt
            status: success
        on_failure:
          put: git-pull-request-resource
          params:
            path: git-pull-request-resource
            context: cargo-fmt
            status: failure

      - task: pr-check-toml-formatting
        timeout: 10m
        image: env-glibc
        config:
          platform: linux
          inputs:
          - name: git-pull-request-resource
          run:
            # user: root
            dir: git-pull-request-resource
            path: sh
            args:
            - -exc
            - |
              taplo fmt --check --diff

        on_success:
          put: git-pull-request-resource
          params:
            path: git-pull-request-resource
            context: taplo-fmt
            status: success
        on_failure:
          put: git-pull-request-resource
          params:
            path: git-pull-request-resource
            context: taplo-fmt
            status: failure

      - in_parallel:
        - task: pr-check-cargo-build
          timeout: 60m
          image: env-glibc
          config:
            platform: linux
            inputs:
            - name: git-pull-request-resource
            caches:
            - path: cargo
            - path: target
            run:
              dir: git-pull-request-resource
              # user: root
              path: sh
              args:
              - -exc
              - |
                export CARGO_HOME="$(pwd)/../cargo"
                export CARGO_TARGET_DIR="$(pwd)/../target"
                export CARGO_INCREMENTAL=0
                env

                sudo dnf install -y rocksdb-devel rocksdb
                sudo chown $(whoami): -Rf ${CARGO_HOME}
                sudo chown $(whoami): -Rf ${CARGO_TARGET_DIR}
                sudo chown $(whoami): -Rf .

                rustup target add wasm32-unknown-unknown
                rustup +stable target add x86_64-unknown-linux-gnu
                cargo +nightly --version
                cargo +stable --version
                rustc +stable --version
                rustc +nightly --version

                cargo +stable build --workspace

          on_success:
            put: git-pull-request-resource
            params:
              path: git-pull-request-resource
              context: cargo-build
              status: success
          on_failure:
            put: git-pull-request-resource
            params:
              path: git-pull-request-resource
              context: cargo-build
              status: failure

        - task: pr-check-clippy
          timeout: 60m
          image: env-glibc
          config:
            platform: linux
            inputs:
            - name: git-pull-request-resource
            caches:
            - path: target
            - path: cargo

            run:
              # user: root
              dir: git-pull-request-resource
              path: sh
              args:
              - -exc
              - |
                export CARGO_HOME="$(pwd)/../cargo"
                export CARGO_TARGET_DIR="$(pwd)/../target"
                export CARGO_INCREMENTAL=0

                sudo chown $(whoami): -Rf ${CARGO_HOME}
                sudo chown $(whoami): -Rf ${CARGO_TARGET_DIR}
                sudo chown $(whoami): -Rf .

                sudo dnf install -y rocksdb-devel rocksdb

                rustup +nightly target add wasm32-unknown-unknown
                rustup +stable target add wasm32-unknown-unknown
                rustup +stable target add x86_64-unknown-linux-gnu
                cargo +nightly --version
                cargo +stable --version
                rustc +stable --version
                rustc +nightly --version

                cargo clippy --workspace

          on_success:
            put: git-pull-request-resource
            params:
              path: git-pull-request-resource
              context: cargo-clippy
              status: success
          on_failure:
            put: git-pull-request-resource
            params:
              path: git-pull-request-resource
              context: cargo-clippy
              status: failure

        - task: pr-check-cargo-test
          timeout: 60m
          image: env-glibc
          config:
            platform: linux
            inputs:
            - name: git-pull-request-resource
            caches:
            - path: cargo
            - path: target
            run:
              # user: root
              dir: git-pull-request-resource
              path: sh
              args:
              - -exc
              - |
                export CARGO_HOME="$(pwd)/../cargo"
                export CARGO_TARGET_DIR="$(pwd)/../target"
                export CARGO_INCREMENTAL=0

                sudo chown $(whoami): -Rf ${CARGO_HOME}
                sudo chown $(whoami): -Rf ${CARGO_TARGET_DIR}
                sudo chown $(whoami): -Rf .

                sudo dnf install -y rocksdb-devel rocksdb

                rustup +nightly target add wasm32-unknown-unknown
                rustup target add wasm32-unknown-unknown
                rustup +stable target add x86_64-unknown-linux-gnu
                cargo +nightly --version
                cargo +stable --version
                rustc +stable --version
                rustc +nightly --version

                cargo +stable test

          on_success:
            put: git-pull-request-resource
            params:
              path: git-pull-request-resource
              context: cargo-test
              status: success
          on_failure:
            put: git-pull-request-resource
            params:
              path: git-pull-request-resource
              context: cargo-test
              status: failure

  ####################################################################################
  #                                 M A S T E R
  ####################################################################################
  - name: base-verify
    build_logs_to_retain: 10
    public: true
    serial: true
    plan:
    - in_parallel:
      - get: env-glibc
      - get: git-repo
        resource: git-clone-resource
        version: every
        trigger: true

    - in_parallel:
      - do:
        - task: verify-cargo-build
          timeout: 60m
          image: env-glibc
          config:
            platform: linux
            inputs:
            - name: git-repo
            outputs:
            - name: binary
            caches:
            - path: cargo
            - path: target
            run:
              # user: root
              dir: git-repo
              path: sh
              args:
              - -exc
              - |
                export RUST_BACKTRACE=full
                export CARGO_HOME="$(pwd)/../cargo"
                export CARGO_TARGET_DIR="$(pwd)/../target"
                export CARGO_INCREMENTAL=0

                sudo chown $(whoami): -Rf ${CARGO_HOME}
                sudo chown $(whoami): -Rf ${CARGO_TARGET_DIR}
                sudo chown $(whoami): -Rf .
                sudo chown $(whoami): -Rf ../binary

                rustup target add wasm32-unknown-unknown
                rustup +stable target add x86_64-unknown-linux-gnu
                cargo +nightly --version
                cargo +stable --version
                rustc +stable --version
                rustc +nightly --version

                cargo +stable build --release --workspace

        - task: verify-cargo-test
          timeout: 60m
          image: env-glibc
          config:
            platform: linux
            inputs:
            - name: git-repo
            caches:
            - path: cargo
            run:
              # user: root
              dir: git-repo
              path: sh
              args:
              - -exc
              - |
                export RUST_BACKTRACE=1
                export CARGO_HOME="$(pwd)/../cargo"
                export CARGO_INCREMENTAL=0

                sudo chown $(whoami): -Rf ${CARGO_HOME} .

                rustup target add wasm32-unknown-unknown
                rustup +stable target add x86_64-unknown-linux-gnu
                cargo +nightly --version
                cargo +stable --version
                rustc +stable --version
                rustc +nightly --version

                cargo +stable test

      - task: verify-cargo-fmt
        timeout: 15m
        image: env-glibc
        config:
          platform: linux
          inputs:
          - name: git-repo
          caches:
          - path: cargo
          run:
            # user: root
            dir: git-repo
            path: sh
            args:
            - -exc
            - |
              export CARGO_HOME="$(pwd)/../cargo"
              export CARGO_INCREMENTAL=0

              sudo chown $(whoami): -Rf ${CARGO_HOME} .
              cargo +nightly --version

              cargo +nightly fmt -- --check


      - task: verify-taplo-fmt
        timeout: 15m
        image: env-glibc
        config:
          platform: linux
          inputs:
          - name: git-repo
          caches:
          - path: cargo
          run:
            # user: root
            dir: git-repo
            path: sh
            args:
            - -exc
            - |
              export CARGO_HOME="$(pwd)/../cargo"
              export CARGO_INCREMENTAL=0

              sudo chown $(whoami): -Rf ${CARGO_HOME} .

              taplo fmt --check --diff
